
IF NOT EXISTS 
    (SELECT 1  
     FROM master.sys.server_principals
     WHERE name = 'IIS APPPOOL\Auth')
BEGIN
    CREATE LOGIN [IIS APPPOOL\Auth] FROM WINDOWS;
END

IF NOT EXISTS
    (SELECT 1
     FROM sys.database_principals
     WHERE name='AUTHAPI_SVCACCT')
BEGIN
    CREATE USER [AUTHAPI_SVCACCT] FOR LOGIN [IIS APPPOOL\Auth];
END

ALTER ROLE [db_owner] ADD MEMBER [AUTHAPI_SVCACCT]
